### ISSUE TITLE
멘토로 참여하게 된 이혁진입니다.

### ISSUE THREAD

**Issue by hyukjin-lee** [JNU-econovation/contents-proxy-blog-team1#1]
이번 해커톤 프로젝트의 사용자의 시나리오는

1. github, evernote, dropbox등 어딘가에 글을 등록한다.
2. contents-proxy-blog 에 와서 1에서 작성한 글을 찾을수 있는 정보를 입력한다. ( 예를 들면 github 이슈라면 이슈 URL)
3. 블로그에서 1에서 입력한 글을 볼수 있다.

어떤 저장소를 먼저 연동할지는 조사를 해보고 ROI가 높아 보이는 것부터 시도해보는게 좋겠습니다.

**Comment by hyukjin-lee** [comment]
해당 이슈를 확인했으면 답글을 달아주는걸 규칙으로 하겠습니다. 답글이 다 달린 이슈는 close 하도록 하겠습니다.

**Comment by hyukjin-lee** [comment]
이번 프로젝트는 모든걸 깃헙 이슈기반으로 하겠습니다. 


# 전체 플로우
1. Isuee 발급
2. Issue 작업
3. Pull Request Coide Review 진행
4. Issue 반영

## Issue 발행

### Issue란?
모든것이 이슈라고 볼 수 있습니다. 새로운 추가될 가능, 개선 해야할 가능, 버그 등등 모든것이 이슈라고 볼 수 있습니다. 모든 활동 내역에 대해서 이슈를 등록하고 그 이슈기반으로 작업을 진행하게 됩니다.

## Issue 작업

### 등록된 issue 살펴 보기
![등록된-이슈](https://i.imgur.com/2ciNoCd.png)

* Assignees : 해당 작업의 담당자
* Labels: 해당 작업의 성격
* Milestone: 해당 작업이 속한 파트

![](https://i.imgur.com/DkniJHn.png)

다른 것들은 이해하기 쉬울 텐데 Milestone은 조금 생소할 수 있습니다. Milestone에 간단하게 설명해 드리면 이번 출시 버전이 1.0.0 일 경우 해당 버전이든 이슈(작업) 기능 강화, 새 기능추가, 버그 기타 등등 모든 이슈를 Version 1.0.0 Milestone이라는 항목에 추가하면 위 그림처럼 Version 1.0.0에 대한 전체적인 상황을 한눈에 볼 수가 있는 장점이 있습니다.



### GitHub Pull Request
![github-pull-request](https://i.imgur.com/6bBTJUV.png)

Github Code 텝에서 `New Pull Request` 버튼을 클릭해서 Pull Request를 진행 합니다.

### Pull Request 작성법
![](https://i.imgur.com/3TnHt0c.png)

* 왼쪽 위에 Reviewers 톱니바퀴 버튼을 클릭해서 리뷰어를 지정합니다.
* resolved: #1(해당 Issue Number) 풀리퀘스트 요청하는 이유 즉 무슨 이슈에 대한 작업인지 명시합니다.

`resolved` 키워드를 입력하면 해당 풀리퀘스트가 master Branch에 반영되면 자동으로 close 됩니다. 자동으로 close 되는 것이 싫으시다면 issue: #[해당 Issue Number]를 작성해주세요.

이렇게 Pull Request가 생성되면 새로운 Issue Number가 부여됩니다. **즉 Pull Request도 Issue입니다.**

![issue-pull-request-연결](https://i.imgur.com/skNmpeQ.png)

**반드시 해당 풀리퀘스트가 무슨 이슈에 따른 요청인지 명시하시는 것을 권장합니다.** 그렇게 되면 위 그림처럼 해당 이슈에 #2[방금 요청한 풀리퀘스트]가 연결되어 해당 이슈가 무슨 코드로 인해서 진행됐는지 추적하기 좋습니다.

### Code Review
리뷰어가 요청받은 Pull Request로 가서 `Add your review` 버튼을 클릭합니다.

![리뷰진행](https://i.imgur.com/k11vL5w.png)
소스코드에 대한 질문 등 다양한 comment를 남기는 방식으로 pull reqeust가 진행합니다.

* Approve: 코드에 대한 의문점이 없다면 승인 .
* Comment: 간단한 피드백 제출
* Request changes: 해당 코드에 문제가 있다고 판단되며 코드를 반드시 수정 요구

위 항목은 Comment로 Submit review를 진행했습니다.

![comment-표시](https://i.imgur.com/EHnVEjU.png)
위에서 작성한 comment가 해결됬었다면 `Merge pull request` 버튼을 눌러서 해당 pull request를 반영합니다. 반영이 완료되고 해당 branch가 더는 필요 없다고 판단되시면 `Delete branch` 버튼을 통해서 Remote에 있는 Branch를 삭제할 수 있습니다.

**위에서 작성한 resolved: #1 키워드 덕분에 소스코드가 해당 Branch에 적용됐으니 자동으로 #1에 대한 이슈는 close 처리됩니다.**



# Wiki
GitHub에서는 기본적인 WIKI 기능을 제공해줍니다. 

## Wiki 등록
![](https://github.com/cheese10yun/github/blob/master/images/wiki.gif?raw=true)

## GitHub 작성
![](https://i.imgur.com/t3LuQsm.png)
GitHub에서 위키를 작성할 수 있습니다.

## Local 작성
![](https://i.imgur.com/Ff6Heeb.png)
**위키를 로컬환경에서 작성해서 Push 할 수 있습니다. 이렇게 사용하시는 것을 추천 드립니다.**

**Comment by hyukjin-lee** [comment]
해당 이슈를 확인했으면 답글을 달아주는걸 규칙으로 하겠습니다. 답글이 다 달린 이슈는 close 하도록 하겠습니다.

**Comment by esp2ar0** [comment]
확인이요

**Comment by wijehyeon** [comment]
확인했습니다

**Comment by dadadamarine** [comment]
확인했습니다.
