### ISSUE TITLE
post vs posts 블로그 글 모델명을 정하는 중입니다.

### ISSUE THREAD

**Issue by wijehyeon** [JNU-econovation/contents-proxy-blog-team1#11]
블로그 게시글 객체를 설계하는 중인데
기존에 qna에서나 등등 model/Post 이렇게 단수로 했었는데
jojoldu님의 블로그에서 보면 model/Posts이런식으로 복수로 하던데
뭐가 더 convention에 맞을까요

**Comment by esp2ar0** [comment]
개인적인 생각으로는 Posts라는게 특정적으로 그렇게 쓰인거같고 다른 부분들은 단수인 듯 합니다

**Comment by dadadamarine** [comment]
model은 단수 개체에 대한 속성을 정의한것으므로 post라는 이름이 더 좋을것 같습니다.

**Comment by wijehyeon** [comment]
제 생각은 Post가 될 것 같습니다.
한 단위의 개체로 나눠질 수 있기에 Post라는 "모델", "객체", 그 "존재"를 명시하는 용도로 단수로 사용하는게 맞고
나중에 Repository, List 등의 복수 변수가 되었을 때 Posts라고 사용하도록 하겠습니다. 감사합니다.
