### ISSUE TITLE
[structure 설계] 초기 파일 설계에 대한 논의

### ISSUE THREAD

**Issue by dadadamarine** [JNU-econovation/contents-proxy-blog-team1#12]
컨트롤러, 모델 등 클래스의 네이밍

**Comment by dadadamarine** [comment]
/controller/PostController.java  -> @Controller사용

**Comment by wijehyeon** [comment]
/model/Post.java -> @Entity

**Comment by esp2ar0** [comment]
templates/index.html -> 글 목록 화면
templates/form.html -> 글 등록 화면
templates/show.html -> 글 보기 화면

**Comment by dadadamarine** [comment]
utils/EgitUtil.java

**Comment by dadadamarine** [comment]
exception/FileNotFoundException.java
