### ISSUE TITLE
추가할 의존성, 추가하고싶은 의존성에 대해서 이야기합니다

### ISSUE THREAD

**Issue by wijehyeon** [JNU-econovation/contents-proxy-blog-team1#13]

**Comment by dadadamarine** [comment]
egit -     compile group: 'org.eclipse.mylyn.github', name: 'org.eclipse.egit.github.core', version: '2.1.5'

**Comment by dadadamarine** [comment]
implementation 'org.springframework.boot:spring-boot-starter-web'

**Comment by esp2ar0** [comment]
compile('pl.allegro.tech.boot:handlebars-spring-boot-starter:0.3.0')
handlebars 추가합니다

**Comment by esp2ar0** [comment]
compile('org.springframework.boot:spring-boot-devtools')
devtools 추가

**Comment by esp2ar0** [comment]
compile 'com.vladsch.flexmark:flexmark-all:0.40.20'
flexmark 추가

**Comment by wijehyeon** [comment]
compile('com.evernote:evernote-api:1.25.1')
evernote api 의존성 추가합니다
