### ISSUE TITLE
[egit]url 토큰화 관련 이슈

### ISSUE THREAD

**Issue by dadadamarine** [JNU-econovation/contents-proxy-blog-team1#19]
https://github.com/JNU-econovation/contents-proxy-blog-team1/blob/feature/html/README.md
라는 uri기준으로 egit을 사용하기위해 
1. userId 
2. repository_name
3. branch_name
4. 파일 경로

위 4가지가 필요합니다.

하지만 현재 url상에서 
- branch_name = feature , file_path = /html/README.md 인지
- branch_name = feature/html , file_path = /README.md 인지
구분할 수 없는 이슈가 있습니다.

**Comment by hyukjin-lee** [comment]
createFromUrl 가 static 함수로 제공됩니다.

**Comment by dadadamarine** [comment]
createFromUrl로 uri를 가지고 바로 RepositoryId객체를 만들수 있었습니다.

하지만 여전히 blob/뒤에 filePath와 branch이름을 구분할 수 없는 이슈가 있습니다.

어떻게 처리해야 좋을까요..

**Comment by hyukjin-lee** [comment]
경로가 https://github.com/JNU-econovation/contents-proxy-blog-team1/blob/master/README.md
로 통일되어서 blob master 로 토큰화 하면 될 것 같습니다.

**Comment by dadadamarine** [comment]
다른 branch의 파일을 참조할경우
blob/feature/html/{filePath} 
라는 uri를 사용하게 되는점을 걱정하고 있습니다.
멘토님 말씀대로 이 문제에서는 input을 master branch로 한정지어도 작업해도 될까요?

**Comment by hyukjin-lee** [comment]
다른 브랜치도 결국 master로 머지될텐데 master만 보면 됩니다...
