### ISSUE TITLE
postRepository에서 findById로 post를 가져올 때, 해당하는 id의 post가 없을 경우

### ISSUE THREAD

**Issue by wijehyeon** [JNU-econovation/contents-proxy-blog-team1#22]
사용자화된 Exception구현 vs NoSuchElementException
어떻게 구현할까요?

**Comment by esp2ar0** [comment]
의미를 좀 더 명확하게 하기 위해 사용자화 된 Exception이 좋아보입니다

**Comment by wijehyeon** [comment]
사용자 정의 예외를 만들면 좋은점은 : 에러메세지를 보고 내가 어디서 잘못했는지 정확히 알기가 쉽다? 
사용자화 된 Exception으로 구현하겠습니다.

**Comment by hyukjin-lee** [comment]
단점은 뭐가 있을까요

**Comment by wijehyeon** [comment]
수많은 경우의 예외를 사용자화 하다보면 나중에는 예외가 산처럼 쌓일 것 같습니다.
