### ISSUE TITLE
기본 홈 화면(루트) url 맵핑

### ISSUE THREAD

**Issue by esp2ar0** [JNU-econovation/contents-proxy-blog-team1#26]
현재 루트의 url 맵핑이 없습니다

/posts -> index인데

홈 화면이 따로 없다고 가정하고
index를 홈으로 처리해주는게 어떨까요
(글 목록 보는 뷰)

**Comment by dadadamarine** [comment]
defaultController를 추가해서 posts로 redirect시키면 좋을것 같습니다.
1. posts페이지가 글 리스트를 보여주는 페이지기 때문에 이 모델을 추가하는 소스를 posts를 처리하는 메서드로 재사용 할 수 있음

**Comment by esp2ar0** [comment]
그렇다면 그 하나를 위해 컨트롤러를 추가하기 보다는 qna미션 할 때 했었던 것처럼 config 하나 추가해서 해주면 간단하겠군요
리다이렉트도 가능한지 모르겠네요

**Comment by dadadamarine** [comment]
https://www.logicbig.com/tutorials/spring-framework/spring-web-mvc/url-to-url-redirect.html
다행이 방법이 있네요.
요약 : 
- @Override
    public void addViewControllers (ViewControllerRegistry registry) {
        RedirectViewControllerRegistration r =
                  registry.addRedirectViewController("/test", "/test2");
        r.setStatusCode(HttpStatus.SEE_OTHER);
    }

**Comment by dadadamarine** [comment]
WelcomeController를 추가하는것으로 변경하였습니다.
