### ISSUE TITLE
로그인, 회원가입 및 권한 개발

### ISSUE THREAD

**Issue by esp2ar0** [JNU-econovation/contents-proxy-blog-team1#38]
1. model에 User 추가
- 멤버변수 : id, userId, userName, password, email

2. 관련 컨트롤러 추가

3. 메인 화면인 index에 로그인 기능 추가
- 로그인 한 유저만 글을 쓸 수 있도록
-> 권한체크

4. index, show 화면에 username 표시 기능 추가

**Comment by esp2ar0** [comment]
어떤 데이터베이스에는 user가 키워드인 경우가 있으므로(postgres) account라는 이름으로 짓겠습니다
또한 중복되는걸 없앨게요 (accountName -> name)

**Comment by dadadamarine** [comment]
확인했습니다.

**Comment by esp2ar0** [comment]
## url 맵핑
URL <-> view
post /accounts <-> redirect /
get /accounts/form <-> accounts/form
get /accounts/login <-> accounts/login
post /accounts/login <-> redirect /
get /accounts/logout <-> redirect /
