### ISSUE TITLE
egit라이브러리 사용법 관련

### ISSUE THREAD

**Issue by dadadamarine** [JNU-econovation/contents-proxy-blog-team1#4]
- github api설명 중 repository/gencontent 관련 설명
  https://developer.github.com/v3/repos/contents/#get-contents

- egit  - getcontent 예시파일
  https://github.com/eclipse/egit-github/blob/master/org.eclipse.egit.github.core/src/org/eclipse/egit/github/core/RepositoryContents.java

**Comment by hyukjin-lee** [comment]
egit에 대한 이슈가 아니라 사용법 팁을 정리한 위키같네요
