### ISSUE TITLE
[Entity] 블로그 글 Post객체 모델 생성하기

### ISSUE THREAD

**Issue by wijehyeon** [JNU-econovation/contents-proxy-blog-team1#5]
- 필요 변수
 글 제목
 markdown자료에 대한 github URL 
MVC중 M에 대한 것만

**Comment by wijehyeon** [comment]
글 제목 - String
url - String
다른 의견 있나요

**Comment by dadadamarine** [comment]
markdown 자료를 사용자가 요청할때마다 api를 쓸수가 없으니 등록할때 한번 마크다운 문서를 가져와서 db에 저장하는건 어떨까요

게시글 board에 대한 model

1. id
2. url
3. 가져온 markdown data

**Comment by hyukjin-lee** [comment]
이슈 제목만 보고 뭔 이슈인지 하나도 모르겠습니다.

**Comment by wijehyeon** [comment]
markdown을 DB에  어떤 자료형으로 담을까요
String...으론...

**Comment by wijehyeon** [comment]
qna때처럼
@Lob?

**Comment by dadadamarine** [comment]
LongText or blob

**Comment by hyukjin-lee** [comment]
api 호출을 줄이기위해 한번 가져온 markdown을 db에 넣고 보여주면 어떤 이슈가 발생할 수 있을지 고민해보세요

**Comment by wijehyeon** [comment]
DB검색하는게 또 일입니다

**Comment by dadadamarine** [comment]
db id로 검색합니다.

**Comment by hyukjin-lee** [comment]
아닙니다 해당 깃허브 마크다운이 수정되었음에도 불구하고 예전 내용을 보여주는게 문제로 발생합니다

**Comment by wijehyeon** [comment]
ㅡㅡ 민석이형

**Comment by esp2ar0** [comment]
그러면 내용을 그대로 저장해야겠다 (url)

**Comment by wijehyeon** [comment]
repository 
-> JpaRepository
