### ISSUE TITLE
egit이 필요한가?

### ISSUE THREAD

**Issue by wijehyeon** [JNU-econovation/contents-proxy-blog-team1#6]
주장1. github연동의 의미가 -> github연동해서 repository, markdown파일에 대한 접근으로 기능 구현을 하라
주장2. github연동의 의미가 -> 그냥 깃허브 편하게 사용할 수 있는 기술을 알려준 것이다

**Comment by esp2ar0** [comment]
소스트리 같은 툴처럼 gui적인 플러그인으로써 사용 하라는 것인지 헷갈림

**Comment by wijehyeon** [comment]
처음에는 egit에서 제공해주는 함수들을 활용해서 
사용자가 입력한 주소를통해 repository에 접근, markdown파일에 접근, markdown->html렌더링을 진행하라는 것인줄..
근데 주장2가 맞는것 같은데?

**Comment by dadadamarine** [comment]
1에 한표 
제 이해로는 egit이 GitHub api를 java 소스로 사용하게 해주는 라이브러리 같습니다.
+ 향후 요구사항에 문서에대한 crud 요청 기능들이 올라올 경우를 생각해 url을 통해 가져오는것보다 api연동을 미리해두는게 좋을거같음

**Comment by esp2ar0** [comment]
멘토님 답변 가능한가요

**Comment by hyukjin-lee** [comment]
1번이 맞네요

**Comment by wijehyeon** [comment]
감사합니다 issue 닫습니다.
