### ISSUE TITLE
프론트 구성과 코딩을 어떻게 할 것인가

### ISSUE THREAD

**Issue by esp2ar0** [JNU-econovation/contents-proxy-blog-team1#7]
1. 구성
* 홈 화면
* 글 등록 화면

2. 코딩
* 다른 소스 가져와서 쓰는건 어떨까? - qna게시판 소스

**Comment by wijehyeon** [comment]
스타일은 다른거 가져와도 될 것 같긴 합니다.
아니면 bootstrap에서 가져오던가

**Comment by dadadamarine** [comment]
url구성
posts (get)
posts/1 (get)
posts (post)
posts/form (get)

**Comment by wijehyeon** [comment]
posts라고 알고있습니다

**Comment by wijehyeon** [comment]
- 글 등록화면에는
제목, url입력 두개의 input

**Comment by wijehyeon** [comment]
짠

**Comment by dadadamarine** [comment]
posts : (홈화면) 게시글의 리스트와 + 글 등록 버튼
posts/form :
* 글 등록화면에는
  제목, url입력 두개의 input

posts/1 : (게시글 상세) title, url , html로 변환된 문서의내용
