### ISSUE TITLE
브랜치 관리와 컨벤션을 정해봅시다

### ISSUE THREAD

**Issue by esp2ar0** [JNU-econovation/contents-proxy-blog-team1#9]
이슈 하나(기능 하나)당 하나씩 브랜치를 생성하여 코딩을 다 하고 풀리퀘를 날리자

**Comment by esp2ar0** [comment]
브랜치 컨벤션
1. feature/~~~  
2. bugfix/~~~  
3. Refactor/~~~

**Comment by wijehyeon** [comment]
enhancement인 것들만 Branch로 만들어서 가져가서 작업하고 PR날리면 좋을 것 같습니다.

**Comment by esp2ar0** [comment]
feature인 것들만
